### ISSUE TITLE
Failed to activate the atom-minjs package

### ISSUE THREAD

**Issue by ghost** [mananshah99/atom-minjs#2]
[Enter steps to reproduce below:]
1. Open a javascript file
2. Press Ctrl+S

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-minjs](https://github.com/mananshah99/atom-minjs) package, v0.2.12
### Stack Trace

Failed to activate the atom-minjs package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (C:\Users\inacent\.atom\packages\atom-minjs\lib\minjs.coffee:26:21)
  at Package.module.exports.Package.activateNow (C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:219:20)
  at C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\inacent\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:177:20)

```
### Commands

```
     -0:14.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:13.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 10x -0:12.3.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:10.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:09.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:08.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:08.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:delete (atom-text-editor.editor.is-focused)
 15x -0:08.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:delete (atom-text-editor.editor.is-focused)
  3x -0:06.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:delete (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-minjs, v0.2.12
jsformat, v0.9.0
linter, v0.12.7
linter-bootlint, v0.0.6
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-php, v0.0.15
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by mananshah99** [comment]
This might be because of the new atom update (which introduces some breaking changes); I'll take a look. Thanks!

**Comment by adamsir** [comment]
Still now working.

**Comment by cube-dan** [comment]
bump
