### ISSUE TITLE
Failed to activate the atom-minjs package

### ISSUE THREAD

**Issue by ghost** [mananshah99/atom-minjs#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: MX 18.3
**Thrown From**: [atom-minjs](https://github.com/mananshah99/atom-minjs) package 0.2.12

### Stack Trace

Failed to activate the atom-minjs package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/atom-minjs/lib/minjs.coffee:26:22)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3419283)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3418695)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3416305)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3418555)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3418498)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:381612)
    at /usr/share/atom/resources/app/static/<embedded>:11:935623
    at r (/usr/share/atom/resources/app/static/<embedded>:11:930229)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1127206)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1127360)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1125962)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
     -9:54.4.0 window:toggle-menu-bar (input.hidden-input)
     -9:40.8.0 whitespace:remove-trailing-whitespace (input.hidden-input)
     -9:36.9.0 core:select-all (div.line)
     -9:24 editor:toggle-soft-wrap (input.hidden-input)
     -9:04.5.0 markdown-preview:toggle (input.hidden-input)
 16x -7:40.1.0 core:backspace (input.hidden-input)
  2x -2:37.5.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
atom-minify-stand-alone 0.2.0 
atom-minjs 0.2.12 
html-uglifier 0.1.1 
minify-j-s 2.0.0 
website-minifier 1.4.0 
```

**Comment by anyido** [comment]
i cannot install my app
